bump the syn dependency
and switch to the recommended way to parse tokens: `parse_macro_input!`.

This improves (?) error messages when the user applies one of our attributes to
an item that's not a function.

Consider

``` rust
 #[entry]
static MAIN: () = ();

```

The error message changed from:

```
error: custom attribute panicked
  --> src/main.rs:10:1
   |
10 | #[entry]
   | ^^^^^^^^
   |
   = help: message: `#[entry]` must be applied to a function: ParseError(Some("failed to parse fn item: failed to parse"))
```

to:

```
error: expected `fn`
  --> src/main.rs:11:1
   |
11 | static MAIN: () = ();
   | ^^^^^^

error: aborting due to previous error
```